"""
Pydantic models for the Weekly Product Pulse pipeline.
Shared across all modules for type safety and schema enforcement.
"""

from pydantic import BaseModel, Field


class RawReview(BaseModel):
    """A single review fetched from the app store."""
    text: str
    rating: int = Field(ge=1, le=5)
    date: str
    source: str = "Google Play Store"


class Theme(BaseModel):
    """A clustered review theme."""
    label: str
    description: str
    review_count: int
    is_top_3: bool = False


class Quote(BaseModel):
    """A verbatim (PII-masked) user quote linked to a theme."""
    text: str
    theme_label: str
    rating: int = Field(ge=1, le=5, default=3)


class ActionItem(BaseModel):
    """A specific, actionable recommendation."""
    id: int
    title: str
    description: str
    linked_theme: str


class ThemedAnalysis(BaseModel):
    """Output of the clustering stage — themes + quotes."""
    themes: list[Theme] = Field(max_length=5)
    quotes: list[Quote] = Field(max_length=9)


class PulsePayload(BaseModel):
    """
    The complete Weekly Product Pulse — passed through the entire pipeline.
    Generated by Module A, reviewed in Module C, exported by Module B, stored by Module D.
    """
    metadata: dict  # app_name, source, review_count, generated_at
    themes: list[Theme]
    quotes: list[Quote]
    summary_note: str
    action_items: list[ActionItem] = Field(max_length=3)
    footer: str
    approval_status: str = "PENDING"  # PENDING | APPROVED | REJECTED


class FeeExplainerResult(BaseModel):
    """Output of the fee explainer — exit load bullets + sources."""
    scenario: str              # e.g. "Exit Load"
    bullets: list[str] = Field(max_length=5) # 5 bullet points
    source_links: list[str] = Field(max_length=2) # 2 official URLs
    last_checked: str          # e.g. "24 Mar 2026"
